CREATE TABLE QuizDim (
  `id` bigint(20) DEFAULT NULL,
  `canvas_id` bigint(20) DEFAULT NULL,
  `root_account_id` bigint(20) DEFAULT NULL,
  `name` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `points_possible` double DEFAULT NULL,
  `description` text COLLATE utf8mb4_unicode_ci,
  `quiz_type` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `course_id` bigint(20) DEFAULT NULL,
  `assignment_id` bigint(20) DEFAULT NULL,
  `workflow_state` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `scoring_policy` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `anonymous_submissions` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `display_questions` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `answer_display_order` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `go_back_to_previous_question` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `could_be_locked` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `browser_lockdown` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `browser_lockdown_for_displaying_results` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `browser_lockdown_monitor` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ip_filter` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `show_results` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `show_correct_answers` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `show_correct_answers_at` timestamp NULL DEFAULT NULL,
  `hide_correct_answers_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `published_at` timestamp NULL DEFAULT NULL,
  `unlock_at` timestamp NULL DEFAULT NULL,
  `lock_at` timestamp NULL DEFAULT NULL,
  `due_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  KEY `id_idx` (`id`),
  KEY `course_id_idx` (`course_id`),
  KEY `assignment_id_idx` (`assignment_id`)
) ENGINE=MyISAM;
